import "../sass/global.scss";

//const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "IST 363 spotify",
  description: "Generated by wordpress",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
